//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b01 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 11:20:46 AM CEST 
//

package v2_0;

import javax.xml.bind.annotation.*;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.sun.java.xml.ns.persistence package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.sun.java.xml.ns.persistence
	 */
	public ObjectFactory() {}

	/**
	 * Create an instance of {@link Persistence }
	 */
	public Persistence createPersistence() {
		return new Persistence();
	}

	/**
	 * Create an instance of {@link Persistence.PersistenceUnit }
	 */
	public Persistence.PersistenceUnit createPersistencePersistenceUnit() {
		return new Persistence.PersistenceUnit();
	}

	/**
	 * Create an instance of {@link Persistence.PersistenceUnit.Properties }
	 */
	public Persistence.PersistenceUnit.Properties createPersistencePersistenceUnitProperties() {
		return new Persistence.PersistenceUnit.Properties();
	}

	/**
	 * Create an instance of
	 * {@link Persistence.PersistenceUnit.Properties.Property }
	 */
	public Persistence.PersistenceUnit.Properties.Property createPersistencePersistenceUnitPropertiesProperty() {
		return new Persistence.PersistenceUnit.Properties.Property();
	}

}
